[lint]
extend-select = ["quotes", "TESTTHAT", "t_and_f_symbol"]
ignore = ["expect_type"]
exclude = ["inst/", "vignettes/"]
fixable = ["ALL"]
fix-roxygen = true

[lint.assignment]
operator = "<-"

[lint.quotes]
quote = "double"